name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
    contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make

      - name: Build
        run: bash cicd/build.sh

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix7-binary
          path: usr/bin/matrix7

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: matrix7-binary
          path: usr/bin/

      - name: Make binary executable
        run: chmod +x usr/bin/matrix7

      - name: Run tests
        run: bash cicd/test.sh

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: matrix7-binary
          path: usr/bin/

      - name: Make binary executable
        run: chmod +x usr/bin/matrix7

      - name: Install dpkg-deb
        run: sudo apt-get update && sudo apt-get install -y dpkg

      - name: Build .deb package
        run: bash cicd/package.sh

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: trrs1-deb-package
          path: pkg/trrs1_*.deb
